Started by user [8mha:////4Nw2w4KL9NeMiRb1nl0H9jz7+tOgqAKaQPnG6rMPhAH0AAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0madmin
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/triggerjob
################################################################################################################
  Parameterized Remote Trigger Configuration:
    - job:                     test 
    - remoteJenkinsName:       RemoteJenkins
    - auth:                    'Credentials Authentication' as user 'jenkins2' (Credentials ID '36160c8d-fa61-48aa-8f2f-52dc4117d2b2')
    - parameters:              [NAME=test]
    - blockBuildUntilComplete: false
    - connectionRetryLimit:    5
    - trustAllCertificates:    true
################################################################################################################
Connection to remote server failed , waiting to retry - 10 seconds until next attempt. URL: https://35.238.120.231:8080/job/test/api/json, parameters: 
Retry attempt #1 out of 5
Connection to remote server failed , waiting to retry - 10 seconds until next attempt. URL: https://35.238.120.231:8080/job/test/api/json, parameters: 
Retry attempt #2 out of 5
Connection to remote server failed , waiting to retry - 10 seconds until next attempt. URL: https://35.238.120.231:8080/job/test/api/json, parameters: 
Retry attempt #3 out of 5
Connection to remote server failed , waiting to retry - 10 seconds until next attempt. URL: https://35.238.120.231:8080/job/test/api/json, parameters: 
Retry attempt #4 out of 5
Connection to remote server failed , waiting to retry - 10 seconds until next attempt. URL: https://35.238.120.231:8080/job/test/api/json, parameters: 
Retry attempt #5 out of 5
FATAL: Max number of connection retries have been exeeded.
org.jenkinsci.plugins.ParameterizedRemoteTrigger.exceptions.ExceedRetryLimitException: Max number of connection retries have been exeeded.
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.sendHTTPCall(HttpHelper.java:569)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.sendHTTPCall(HttpHelper.java:564)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.sendHTTPCall(HttpHelper.java:564)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.sendHTTPCall(HttpHelper.java:564)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.sendHTTPCall(HttpHelper.java:564)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.sendHTTPCall(HttpHelper.java:564)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.tryCall(HttpHelper.java:603)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.tryGet(HttpHelper.java:623)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.doGet(RemoteBuildConfiguration.java:918)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.getRemoteJobMetadata(RemoteBuildConfiguration.java:1094)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.performTriggerAndGetQueueId(RemoteBuildConfiguration.java:646)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.perform(RemoteBuildConfiguration.java:613)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.perform(RemoteBuildConfiguration.java:579)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1853)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:427)
Finished: FAILURE
